spring:
  application:
    name: analytics-processor
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:worker}

server:
  port: 8080

kinesis:
  stream:
    name: UserMetricsStream

aggregator:
  url: http://dashboard-ingestion-service.default.svc.cluster.local:8080/api/metrics/partial

logging:
  level:
    com.analytics: DEBUG
