apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-aggregator
  namespace: default
  labels:
    app: dashboard-ingestion # Match the service selector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard-ingestion
  template:
    metadata:
      labels:
        app: dashboard-ingestion
    spec:
      serviceAccountName: analytics-consumer
      containers:
      - name: aggregator
        image: 327444422515.dkr.ecr.us-east-1.amazonaws.com/analytics-processor:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "aggregator"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
