apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-consumer
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::327444422515:role/MessageOrderingAnalyticsPodRole
