apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: dashboard-ingestion-vpa
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dashboard-ingestion
  updatePolicy:
    updateMode: "Off" # Recommendations only, applied manually by the CronJob when HPA maxes out
