apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: analytics-worker-vpa
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analytics-worker-vertical
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: 'worker'
        minAllowed:
          cpu: 200m
          memory: 256Mi
        maxAllowed:
          cpu: 2000m
          memory: 2Gi
